export const teams = [
  {
    division: "Summer Men's 24 | Summer Men's B Division",
    team_name: "Brexit Boys",
    day_constraint_1: "Friday",
    day_constraint_2: "",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Disorderly Conduct",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed A Division",
    team_name: "Dream Team",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed A Division",
    team_name: "Hispano's",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed A Division",
    team_name: "Kicking and Screening",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed A Division",
    team_name: "The Good The Bad & The Ugly",
    day_constraint_1: "Monday",
    day_constraint_2: "Tuesday",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed B Division",
    team_name: "Internationals FC (Coed)",
    day_constraint_1: "Monday",
    day_constraint_2: "Friday",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed B Division",
    team_name: "The Somebodies",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed B Division",
    team_name: "Unathletico FC",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed B Division",
    team_name: "Vicious & Delicious",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    team_name: "About to get Messi",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    team_name: "FC Toepokes",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    team_name: "Left Overs",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    team_name: "Liverfools",
    day_constraint_1: "Thursday",
    day_constraint_2: "",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    team_name: "Who Knows ",
    day_constraint_1: "Monday",
    day_constraint_2: "",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    team_name: "Y-Knots",
    day_constraint_1: "Thursday",
    day_constraint_2: "Tuesday",
    time_preference: "early",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    team_name: "Cy-Kick FC",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    team_name: "Forfeit",
    day_constraint_1: "Thursday",
    day_constraint_2: "",
    time_preference: "early",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    team_name: "Inferno Birdo",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    team_name: "Purple Cobras",
    day_constraint_1: "Friday",
    day_constraint_2: "Monday",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    team_name: "SAVAGE'S",
    day_constraint_1: "Thursday",
    day_constraint_2: "Friday",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    team_name: "The Scrubz",
    day_constraint_1: "Monday",
    day_constraint_2: "Tuesday",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    team_name: "Yellow Jackets",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "AFC Richmond",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Arsenal",
    day_constraint_1: "Wednesday",
    day_constraint_2: "Friday",
    time_preference: "late",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Chubby Squonks",
    day_constraint_1: "Monday",
    day_constraint_2: "Wednesday",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Fuego Co-Ed",
    day_constraint_1: "Monday",
    day_constraint_2: "Tuesday",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Fuego women",
    day_constraint_1: "Monday",
    day_constraint_2: "Tuesday",
    time_preference: "middle",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Hakuna Matata",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Hub City United",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    team_name: "Them",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's A Division",
    team_name: "Cyclops FC",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's A Division",
    team_name: "Frigoles",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's A Division",
    team_name: "HighPoint X",
    day_constraint_1: "Thursday",
    day_constraint_2: "Wednesday",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's A Division",
    team_name: "Latinos",
    day_constraint_1: "Thursday",
    day_constraint_2: "Friday",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's A Division",
    team_name: "Los Reyes",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's A Division",
    team_name: "Michoacán FC",
    day_constraint_1: "Monday",
    day_constraint_2: "",
    time_preference: "middle",
  },
  {
    division: "Summer Men's 24 | Summer Men's B Division",
    team_name: "Autlan FC",
    day_constraint_1: "Thursday",
    day_constraint_2: "Friday",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's B Division",
    team_name: "Internationals FC",
    day_constraint_1: "Monday",
    day_constraint_2: "Friday",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's B Division",
    team_name: "FC Barca",
    day_constraint_1: "Monday",
    day_constraint_2: "",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's C Division",
    team_name: "ATLAS",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's C Division",
    team_name: "Ballers",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's C Division",
    team_name: "Lubbock Cruz Azul",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's C Division",
    team_name: "S.O.L",
    day_constraint_1: "Friday",
    day_constraint_2: "",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's C Division",
    team_name: "TOMA",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's D Division",
    team_name: "Dadadors",
    day_constraint_1: "Wednesday",
    day_constraint_2: "Tuesday",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's D Division",
    team_name: "Lobos",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's D Division",
    team_name: "NBC FC",
    day_constraint_1: "Monday",
    day_constraint_2: "Tuesday",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's D Division",
    team_name: "Panthers FC",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's D Division",
    team_name: "Sub Bup",
    day_constraint_1: "Wednesday",
    day_constraint_2: "Friday",
    time_preference: "late",
  },
  {
    division: "Summer Men's 24 | Summer Men's D Division",
    team_name: "Young brothers",
    day_constraint_1: "Thursday",
    day_constraint_2: "",
    time_preference: "middle",
  },
  {
    division: "Summer Men's 24 | Summer Men's E Division",
    team_name: "B-Team Boys",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's E Division",
    team_name: "Cobras FC",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's E Division",
    team_name: "FC Bravos",
    day_constraint_1: "",
    day_constraint_2: "",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's E Division",
    team_name: "Flatland United",
    day_constraint_1: "Wednesday",
    day_constraint_2: "Tuesday",
    time_preference: "",
  },
  {
    division: "Summer Men's 24 | Summer Men's E Division",
    team_name: "Fuego Men",
    day_constraint_1: "Thursday",
    day_constraint_2: "Friday",
    time_preference: "middle",
  },
  {
    division: "Summer Men's 24 | Summer Men's E Division",
    team_name: "Tigris FC",
    day_constraint_1: "Monday",
    day_constraint_2: "",
    time_preference: "middle",
  },
];
