export const schedule = [
  {
    teamA: "Cyclops FC",
    teamB: "Michoacán FC",
    division: "Summer Men's 24 | Summer Men's A Division",
    dayConstraint1: null,
    dayConstraint2: "Monday",
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: "middle",
    scheduledDay: "Tuesday",
    scheduledTime: "6:00",
    isCompromised: true,
  },
  {
    teamA: "Frigoles",
    teamB: "Los Reyes",
    division: "Summer Men's 24 | Summer Men's A Division",
    dayConstraint1: null,
    dayConstraint2: null,
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: null,
    scheduledDay: "Monday",
    scheduledTime: "6:00",
    isCompromised: true,
  },
  {
    teamA: "HighPoint X",
    teamB: "Latinos",
    division: "Summer Men's 24 | Summer Men's A Division",
    dayConstraint1: "Thursday",
    dayConstraint2: "Thursday",
    dayConstraint3: "Wednesday",
    dayConstraint4: "Friday",
    timePreference1: "late",
    timePreference2: null,
    scheduledDay: "Monday",
    scheduledTime: "9:00",
    isCompromised: true,
  },
  {
    teamA: "Brexit Boys",
    teamB: "RagTags",
    division: "Summer Men's 24 | Summer Men's B Division",
    dayConstraint1: "Friday",
    dayConstraint2: "Thursday",
    dayConstraint3: null,
    dayConstraint4: "Friday",
    timePreference1: "late",
    timePreference2: "late",
    scheduledDay: "Monday",
    scheduledTime: "10:00",
    isCompromised: true,
  },
  {
    teamA: "Autlan FC",
    teamB: "Internationals FC",
    division: "Summer Men's 24 | Summer Men's B Division",
    dayConstraint1: "Thursday",
    dayConstraint2: "Monday",
    dayConstraint3: "Friday",
    dayConstraint4: "Friday",
    timePreference1: "late",
    timePreference2: "late",
    scheduledDay: "Tuesday",
    scheduledTime: "9:00",
    isCompromised: true,
  },
  {
    teamA: "ATLAS",
    teamB: "TOMA",
    division: "Summer Men's 24 | Summer Men's C Division",
    dayConstraint1: null,
    dayConstraint2: null,
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: null,
    scheduledDay: "Tuesday",
    scheduledTime: "7:00",
    isCompromised: true,
  },
  {
    teamA: "Internationals FC (Coed)",
    teamB: "Unathletico FC",
    division: "Summer Co-Ed 24 | Co-Ed B Division",
    dayConstraint1: "Monday",
    dayConstraint2: null,
    dayConstraint3: "Friday",
    dayConstraint4: null,
    timePreference1: "late",
    timePreference2: "middle",
    scheduledDay: "Wednesday",
    scheduledTime: "11:00",
    isCompromised: true,
  },
  {
    teamA: "Swamp Donkeys",
    teamB: "The Somebodies",
    division: "Summer Co-Ed 24 | Co-Ed B Division",
    dayConstraint1: null,
    dayConstraint2: null,
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: "late",
    scheduledDay: "Thursday",
    scheduledTime: "8:00",
    isCompromised: true,
  },
  {
    teamA: "About to get Messi",
    teamB: "Y-Knots",
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    dayConstraint1: null,
    dayConstraint2: "Thursday",
    dayConstraint3: null,
    dayConstraint4: "Tuesday",
    timePreference1: null,
    timePreference2: "early",
    scheduledDay: "Monday",
    scheduledTime: "7:00",
    isCompromised: true,
  },
  {
    teamA: "FC Toepokes",
    teamB: "Who Knows",
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    dayConstraint1: null,
    dayConstraint2: "Monday",
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: "middle",
    scheduledDay: "Thursday",
    scheduledTime: "9:00",
    isCompromised: true,
  },
  {
    teamA: "Left Overs",
    teamB: "Liverfools",
    division: "Summer Co-Ed 24 | Co-Ed C Division",
    dayConstraint1: null,
    dayConstraint2: "Thursday",
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: "middle",
    scheduledDay: "Wednesday",
    scheduledTime: "6:00",
    isCompromised: true,
  },
  {
    teamA: "Booballs",
    teamB: "Yellow Jackets",
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    dayConstraint1: null,
    dayConstraint2: null,
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: null,
    scheduledDay: "Thursday",
    scheduledTime: "10:00",
    isCompromised: true,
  },
  {
    teamA: "Cy-Kick FC",
    teamB: "The Scrubz",
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    dayConstraint1: null,
    dayConstraint2: "Monday",
    dayConstraint3: null,
    dayConstraint4: "Tuesday",
    timePreference1: null,
    timePreference2: "middle",
    scheduledDay: "Wednesday",
    scheduledTime: "8:00",
    isCompromised: true,
  },
  {
    teamA: "Forfeit",
    teamB: "SAVAGE'S",
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    dayConstraint1: "Thursday",
    dayConstraint2: "Thursday",
    dayConstraint3: null,
    dayConstraint4: "Friday",
    timePreference1: "early",
    timePreference2: "late",
    scheduledDay: "Wednesday",
    scheduledTime: "7:00",
    isCompromised: true,
  },
  {
    teamA: "Hooligans",
    teamB: "Purple Cobras",
    division: "Summer Co-Ed 24 | Co-Ed D Division",
    dayConstraint1: null,
    dayConstraint2: "Friday",
    dayConstraint3: null,
    dayConstraint4: "Monday",
    timePreference1: null,
    timePreference2: "middle",
    scheduledDay: "Thursday",
    scheduledTime: "11:00",
    isCompromised: true,
  },
  {
    teamA: "Disorderly Conduct",
    teamB: "Them",
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    dayConstraint1: null,
    dayConstraint2: null,
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: "late",
    timePreference2: null,
    scheduledDay: "Friday",
    scheduledTime: "8:00",
    isCompromised: true,
  },
  {
    teamA: "Hakuna Matata",
    teamB: "Hub City United",
    division: "Summer Co-Ed 24 | Co-Ed E Division",
    dayConstraint1: null,
    dayConstraint2: null,
    dayConstraint3: null,
    dayConstraint4: null,
    timePreference1: null,
    timePreference2: null,
    scheduledDay: "Friday",
    scheduledTime: "9:00",
    isCompromised: true,
  },
];
